# Generated by Django 4.2.17 on 2025-04-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='proyectos_imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_set', to='webcitt.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='webcitt.imagen'),
        ),
    ]
