# Generated by Django 4.2.17 on 2025-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0002_imagen_proyecto_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('youtube', 'YouTube')], default='imagen', max_length=10),
        ),
        migrations.AddField(
            model_name='imagen',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos_imagenes/'),
        ),
    ]
