# Generated by Django 4.2.17 on 2025-04-11 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0003_imagen_tipo_imagen_video_url_alter_imagen_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria_submodulo', models.CharField(choices=[('presentacion', 'Presentación'), ('recursosAprendizaje', 'Recursos de Aprendizaje y Práctica')], max_length=50)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='submodulos/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('archivo_html', models.FileField(blank=True, null=True, upload_to='submodulos/html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])])),
                ('imagenes_videos', models.ManyToManyField(blank=True, to='webcitt.imagen')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodulos_set', to='webcitt.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='submodulos',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='webcitt.submodulo'),
        ),
    ]
