# Generated by Django 4.2.17 on 2025-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0004_submodulo_proyecto_submodulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
