# Generated by Django 4.2.17 on 2025-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0005_proyecto_laboratorio_proyecto_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
