# Generated by Django 4.2.17 on 2025-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0006_submodulo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoproyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
