# Generated by Django 4.2.17 on 2025-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0007_estadoproyecto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
