# Generated by Django 4.2.17 on 2025-04-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0008_remove_proyecto_estado_proyecto_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='activo',
            new_name='estado',
        ),
    ]
