# Generated by Django 4.2.17 on 2025-04-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0009_rename_activo_proyecto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='estado',
            new_name='activo',
        ),
    ]
