# Generated by Django 4.2.17 on 2025-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0010_rename_estado_proyecto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
