# Generated by Django 4.2.17 on 2025-04-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0011_proyecto_descripcion_corta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodulo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodulos_set', to='webcitt.proyecto'),
        ),
    ]
