# Generated by Django 4.2.17 on 2025-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0012_alter_submodulo_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos_imagenes/'),
        ),
    ]
