# Generated by Django 4.2.17 on 2025-04-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0013_remove_proyecto_imagenes_proyecto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='submodulos/archivos/')),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_submodulo', to='webcitt.submodulo')),
            ],
        ),
        migrations.AddField(
            model_name='submodulo',
            name='archivos',
            field=models.ManyToManyField(blank=True, related_name='submodulos', to='webcitt.archivosubmodulo'),
        ),
    ]
