# Generated by Django 4.2.17 on 2025-04-11 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webcitt', '0014_archivosubmodulo_submodulo_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
