# Generated by Django 4.2.17 on 2025-04-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0015_alter_proyecto_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodulo',
            name='imagenes_videos',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
