# Generated by Django 4.2.17 on 2025-04-12 01:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0016_remove_submodulo_imagenes_videos_delete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='recursos/archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='CarpetaSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria_recurso', models.CharField(choices=[('presentacion', 'Presentación'), ('recursosAprendizaje', 'Recursos de Aprendizaje y Práctica')], max_length=50)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='recursos/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('archivo_html', models.FileField(blank=True, null=True, upload_to='recursos/html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])])),
                ('activo', models.BooleanField(default=True)),
                ('archivos', models.ManyToManyField(blank=True, related_name='recursos', to='webcitt.archivorecurso')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='webcitt.carpetasubmodulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='submodulo',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='submodulo',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='submodulos',
        ),
        migrations.DeleteModel(
            name='ArchivoSubmodulo',
        ),
        migrations.DeleteModel(
            name='Submodulo',
        ),
        migrations.AddField(
            model_name='recurso',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_set', to='webcitt.proyecto'),
        ),
        migrations.AddField(
            model_name='archivorecurso',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_recurso', to='webcitt.recurso'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='webcitt.recurso'),
        ),
    ]
