# Generated by Django 4.2.17 on 2025-04-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0017_archivorecurso_carpetasubmodulo_recurso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='categoria_recurso',
            new_name='modulo',
        ),
    ]
