# Generated by Django 4.2.17 on 2025-04-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0018_rename_categoria_recurso_recurso_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recurso',
            name='modulo',
            field=models.CharField(choices=[('presentacion', 'Presentación'), ('recursosAprendizaje', 'Recursos de Aprendizaje y Práctica'), ('investigacion', 'Investigación, Innovación y Desarrollo'), ('servicios', 'Servicios y Soporte'), ('colaboracion', 'Colaboración y Networking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='webcitt.carpetarecurso'),
        ),
    ]
