# Generated by Django 4.2.17 on 2025-04-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0019_carpetarecurso_alter_recurso_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='archivos_multimedia',
            field=models.ManyToManyField(blank=True, related_name='recursos_multimedia', to='webcitt.archivorecurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_archivo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('multimedia', 'Multimedia')], default='pdf', max_length=20),
        ),
    ]
