# Generated by Django 4.2.17 on 2025-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0020_recurso_archivos_multimedia_recurso_tipo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='archivo_html',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivos_multimedia',
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/archivos/'),
        ),
    ]
