# Generated by Django 4.2.17 on 2025-04-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0021_remove_recurso_archivo_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='tipo_archivo',
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivos_multimedia',
            field=models.ManyToManyField(blank=True, related_name='recursos_multimedia', to='webcitt.archivorecurso'),
        ),
    ]
