# Generated by Django 4.2.17 on 2025-04-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0022_remove_recurso_tipo_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='es_multimedia',
            field=models.BooleanField(default=False, help_text='Seleccione esta opción si desea subir múltiples archivos multimedia (imágenes o videos).'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, help_text='Tipos de archivo permitidos: PDF, HTML, imágenes (PNG, JPG, GIF) y videos (MP4, AVI, MOV, MKV).', null=True, upload_to='recursos/archivos/'),
        ),
    ]
