# Generated by Django 4.2.17 on 2025-04-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0023_recurso_es_multimedia_alter_recurso_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivos_multimedia',
            field=models.ManyToManyField(blank=True, help_text='Suba múltiples archivos multimedia si la opción multimedia está seleccionada.', related_name='recursos_multimedia', to='webcitt.archivorecurso'),
        ),
    ]
