# Generated by Django 4.2.17 on 2025-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0024_alter_recurso_archivos_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='es_multimedia',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, help_text='Suba un archivo único si lo desea.', null=True, upload_to='recursos/archivos/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivos_multimedia',
            field=models.ManyToManyField(blank=True, help_text='Suba múltiples archivos de cualquier tipo.', related_name='recursos_multimedia', to='webcitt.archivorecurso'),
        ),
    ]
