# Generated by Django 4.2.17 on 2025-04-12 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0025_remove_recurso_es_multimedia_alter_recurso_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('imagen', 'Imagen'), ('video', 'Video'), ('otro', 'Otro')], max_length=10)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='archivorecurso',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivos_multimedia',
        ),
        migrations.AddField(
            model_name='archivorecurso',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivorecurso',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('imagen', 'Imagen'), ('video', 'Video'), ('otro', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivos',
            field=models.ManyToManyField(blank=True, help_text='Suba uno o varios archivos asociados a este recurso.', related_name='recursos', to='webcitt.archivo'),
        ),
    ]
