# Generated by Django 4.2.17 on 2025-04-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0026_archivo_remove_archivorecurso_recurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivos',
            field=models.ManyToManyField(blank=True, help_text='Suba uno o varios archivos asociados a este recurso.', related_name='recursos', to='webcitt.archivorecurso'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece este recurso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_set', to='webcitt.proyecto'),
        ),
    ]
