# Generated by Django 4.2.17 on 2025-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0027_alter_recurso_archivos_alter_recurso_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
