# Generated by Django 4.2.17 on 2025-04-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0028_archivo_url_alter_archivo_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='proyecto',
        ),
    ]
