# Generated by Django 4.2.17 on 2025-04-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0029_remove_recurso_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece este recurso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_set', to='webcitt.proyecto'),
        ),
    ]
