# Generated by Django 4.2.17 on 2025-04-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0030_recurso_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='recursos',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='proyecto',
            field=models.ForeignKey(default=1, help_text='Proyecto al que pertenece este recurso.', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='webcitt.proyecto'),
        ),
    ]
