# Generated by Django 4.2.17 on 2025-04-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0031_remove_proyecto_recursos_alter_recurso_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
