# Generated by Django 4.2.17 on 2025-04-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0032_delete_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoProyecto',
        ),
    ]
