# Generated by Django 4.2.17 on 2025-04-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0033_delete_estadoproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivorecurso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='archivorecurso',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivorecurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/archivos/'),
        ),
    ]
