# Generated by Django 4.2.17 on 2025-04-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0034_remove_archivorecurso_nombre_archivorecurso_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='dependencia',
            field=models.CharField(blank=True, choices=[('san_francisco', 'Centro Experimental - San Francisco'), ('alfonso_tadeo', 'Centro Experimental - Alfonso Tadeó'), ('realidad_virtual', 'Laboratorio de Realidad Virtual - Extendida (Logística)'), ('fablab', 'Laboratorio Fablab'), ('lacteos', 'Planta de Procesamiento de Productos Lácteos'), ('robotica', 'Laboratorio de Robótica y Electrónica Aplicada'), ('multimedia', 'Laboratorio de Formación Informativa de Multimedia'), ('diagnostico', 'Laboratorio Investigación de Diagnóstico Serológico Molecular'), ('turismo', 'Laboratorio de Turismo del Carchi'), ('sensorial', 'Laboratorio de Evaluación Sensorial de Alimentos'), ('asuntos_publicos', 'Laboratorio de Asuntos Públicos')], help_text='Seleccione la dependencia asociada al proyecto.', max_length=50, null=True),
        ),
    ]
