# Generated by Django 4.2.17 on 2025-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0035_proyecto_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
