# Generated by Django 4.2.17 on 2025-05-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0036_proyecto_likes_proyecto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetarecurso',
            name='modulo',
            field=models.CharField(choices=[('presentacion', 'Presentación'), ('recursosAprendizaje', 'Recursos de Aprendizaje y Práctica'), ('investigacion', 'Investigación, Innovación y Desarrollo'), ('servicios', 'Servicios y Soporte'), ('colaboracion', 'Colaboración y Networking')], default='presentacion', max_length=50),
        ),
        migrations.AddField(
            model_name='carpetarecurso',
            name='proyecto',
            field=models.ForeignKey(default=1, help_text='Proyecto al que pertenece esta carpeta.', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='webcitt.proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpetarecurso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='carpetarecurso',
            unique_together={('nombre', 'proyecto')},
        ),
    ]
