# Generated by Django 4.2.17 on 2025-06-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0036_proyecto_likes_proyecto_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarpetaSubmodulo',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='modulo',
        ),
        migrations.AddField(
            model_name='carpetarecurso',
            name='modulo',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('recursosAprendizaje', 'Recursos de Aprendizaje y Práctica'), ('investigacion', 'Investigación, Innovación y Desarrollo'), ('servicios', 'Servicios y Soporte'), ('colaboracion', 'Colaboración y Networking')], default='inicio', max_length=50),
        ),
        migrations.AddField(
            model_name='carpetarecurso',
            name='proyecto',
            field=models.ForeignKey(default=1, help_text='Proyecto al que pertenece esta carpeta.', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='webcitt.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, help_text='Suba un archivo ZIP que contenga un archivo HTML.', null=True, upload_to='recursos/archivos/'),
        ),
        migrations.AlterField(
            model_name='carpetarecurso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='proyecto',
            field=models.ForeignKey(help_text='Proyecto al que pertenece este recurso.', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='webcitt.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='carpetarecurso',
            unique_together={('nombre', 'proyecto')},
        ),
    ]
