# Generated by Django 4.2.17 on 2025-06-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0037_delete_carpetasubmodulo_remove_recurso_archivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpetarecurso',
            name='proyecto',
            field=models.ForeignKey(default=1, help_text='Proyecto al que pertenece esta carpeta.', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='webcitt.proyecto'),
        ),
        migrations.CreateModel(
            name='CarpetaSubmodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece esta carpeta de submódulo.', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_submodulo', to='webcitt.proyecto')),
            ],
        ),
    ]
