# Generated by Django 4.2.17 on 2025-05-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0037_carpetarecurso_modulo_carpetarecurso_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='modulo',
        ),
    ]
