# Generated by Django 4.2.17 on 2025-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0038_remove_recurso_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='archivos',
        ),
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, help_text='Suba un archivo asociado a este recurso.', null=True, upload_to='recursos/archivos/'),
        ),
    ]
