# Generated by Django 4.2.17 on 2025-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcitt', '0039_remove_recurso_archivos_recurso_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, help_text='Suba un archivo ZIP que contenga un archivo HTML.', null=True, upload_to='recursos/archivos/'),
        ),
    ]
