# Generated by Django 5.1.4 on 2024-12-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prject',
            new_name='Project',
        ),
    ]
